### ISSUE TITLE
Breakage if node-semver is installed

### ISSUE THREAD

**Issue by jayvdb** [storyscript/cli#298]
After importing `semver`, it is necessary to check it is the correct semver.  c.f. https://github.com/k-bx/python-semver/issues/67

If it is the wrong one, the following occurs.

```py
Traceback (most recent call last):
  File "/usr/bin/story", line 11, in <module>
    load_entry_point('story', 'console_scripts', 'story')()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jayvdb/projects/storyscript/cli/story/cli.py", line 398, in cli
    ensure_latest()
  File "/home/jayvdb/projects/storyscript/cli/story/ensure.py", line 49, in ensure_latest
    if semver.cmp(current_version, latest_version) == -1:
TypeError: cmp() missing 2 required positional arguments: 'b' and 'loose'
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

The other repo is at https://github.com/podhmo/python-semver .

A useful way to differentiate them is that the `node-semver` has an attribute `semver.SEMVER_SPEC_VERSION`.

A try block to access that field will allow detection, in which case a helpful message can be shown, and/or the version check can be skipped.

**Comment by jayvdb** [comment]
The semver dependency can probably be dropped, and replaced with stdlib distutils `LooseVersion` without significant lose of functionality or increase in complexity.

Probably it will be less complicated and brittle, because ensure is doing its own version parsing  `story_version.split('.')[:3]`.
