### ISSUE TITLE
Login through CLI doesn't work

### ISSUE THREAD

**Issue by daaAd1** [storyscript/cli#328]
**Description**

**Steps to reproduce the issue:**
1. Click Continue with GitHub [on this page](https://storyscript.io/pricing)
2. After login click on create app, get redirected to Let's get started page
3. Run `sudo snap install story` in cli
4. Run `story login`

**Describe the results you received:**
```
The following network error occurred:
HTTPSConnectionPool(host='stories.storyscriptapp.com', port=443): 
Max retries exceeded with url:
 /github/oauth_callback?state=215ee9de-78b4-4d8c-852f-21abb3b1a78a
 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f03f6415710>: 
Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Describe the results you expected:**
I expected to be logged in.

**Output of `storyscript version`:**
I am outputting `story --version` command

```
Storyscript CLI: v0.21.4, Storyscript Compiler: v0.24.2.
```

**Additional info**
I am running ManjaroLinux, version 18.1.1. CLI commands where run in zsh environment.

**Comment by wilzbach** [comment]
@daaAd1 
- sorry to hear that you're experiencing this
- I moved your issue over to the CLI repo
- this issue sounds similar to https://github.com/storyscript/cli/issues/246

Is there anything special about your system? Maybe a proxy?

**Comment by daaAd1** [comment]
I wasn't using any proxy. I am using snap in version 2.42-1. 

Thanks for linking the issue, I did install it story through `pip install story` command and it worked.

I wasnt't able to find any similar issues so I created new one, but I see issue #246 exists so this can be closed if you don't need any more info from me.

**Comment by williammartin** [comment]
I was able to reproduce this just now:

```
○ → vagrant init ubuntu/bionic64
...
○ → vagrant up
...
○ → vagrant ssh
... 
vagrant@ubuntu-bionic:~$ sudo snap install story
2019-10-28T10:59:36Z INFO Waiting for restart...
story 0.21.4 from Storyscript installed

vagrant@ubuntu-bionic:~$ story login
Hi! Thank you for using Storyscript Cloud.
Please login with GitHub to get started.

Visit this link if your browser doesn't open automatically:
https://stories.storyscriptapp.com/github?state=e58a5481-9620-4800-8a36-dfae657b1c32

⠋The following network error occurred:
        HTTPSConnectionPool(host='stories.storyscriptapp.com', port=443): Max retries exceeded with url: /github/oauth_callback?state=e58a5481-9620-4800-8a36-dfae657b1c32 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1ee979ca20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
The Storyscript Cloud CLI will retry automatically...
```

**Comment by wilzbach** [comment]
@jtarun4625 we just released `0.21.6` which contains updated confinement rules (see e.g. https://github.com/storyscript/cli/pull/333). Could you perhaps give this release a try to see whether it fixed your issue? Thanks!

**Comment by wilzbach** [comment]
@daaAd1 we just released 0.21.6 which contains updated confinement rules (see e.g. #333). Could you perhaps give this release a try to see whether it fixed your issue? Thanks!

(I reopened this as I wanted to make sure that you are not experiencing this anymore.)

**Comment by daaAd1** [comment]
So I did following steps now:

1. pip uninstall story 
got this output - `Successfully uninstalled story-0.21.4`
2. snap install story
got this output - `story 0.22.0 from Storyscript installed`
3. story login
browser opened login page, welcome page was shown but I got this output back in terminal
```
Traceback (most recent call last):
  File "/snap/story/30/bin/story", line 11, in <module>
    load_entry_point('story==0.22.0', 'console_scripts', 'story')()
  File "/snap/story/30/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/snap/story/30/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/snap/story/30/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/story/30/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/story/30/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/snap/story/30/lib/python3.6/site-packages/story/commands/login.py", line 11, in login
    cli.user()
  File "/snap/story/30/lib/python3.6/site-packages/story/cli.py", line 218, in user
    initiate_login()
  File "/snap/story/30/lib/python3.6/site-packages/story/cli.py", line 180, in initiate_login
    if r.json().get('beta') is False:
AttributeError: 'str' object has no attribute 'get'
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

Hope this helps
