### ISSUE TITLE
asyncy cli from snap appears broken

### ISSUE THREAD

**Issue by williammartin** [storyscript/cli#53]
```
vagrant@ubuntu-bionic:~$ uname -a
Linux ubuntu-bionic 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
vagrant@ubuntu-bionic:~$ sudo snap install --edge --devmode asyncy
2018-12-05T17:33:00Z INFO Waiting for restart...
asyncy (edge) 0.0.11 from 'steveasyncy' installed
```

```
vagrant@ubuntu-bionic:~$ asyncy
Traceback (most recent call last):
  File "/snap/asyncy/63/bin/asyncy", line 11, in <module>
    load_entry_point('asyncy==0.0.11', 'console_scripts', 'asyncy')()
  File "/snap/asyncy/63/lib/python3.5/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/snap/asyncy/63/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "/snap/asyncy/63/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/snap/asyncy/63/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/snap/asyncy/63/lib/python3.5/site-packages/cli/main.py", line 3, in <module>
    from .cli import cli
  File "/snap/asyncy/63/lib/python3.5/site-packages/cli/cli.py", line 30
    dc = f'docker-compose -f {home}/docker-compose.yml'
```

**Comment by williammartin** [comment]
By the look of the other Traceback in #54, I'm guessing this package is extremely old :)

**Comment by judepereira** [comment]
Yes, this is old. I'll release the latest version shortly.

**Comment by judepereira** [comment]
Closing since we've now automated snap releases.
