### ISSUE TITLE
asyncy login results prints traceback on macOSX

### ISSUE THREAD

**Issue by williammartin** [storyscript/cli#54]
Right after `brew install`:

```
→ asyncy login
Traceback (most recent call last):
  File "/usr/local/bin/asyncy", line 11, in <module>
    load_entry_point('asyncy==0.2.3', 'console_scripts', 'asyncy')()
  File "/usr/local/Cellar/asyncy/0.2.3/libexec/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/asyncy/0.2.3/libexec/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/asyncy/0.2.3/libexec/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/asyncy/0.2.3/libexec/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/asyncy/0.2.3/libexec/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/asyncy/0.2.3/libexec/lib/python3.7/site-packages/cli/commands/login.py", line 13, in login
    click.style(cli.data['email'], fg='cyan')
  File "/usr/local/Cellar/asyncy/0.2.3/libexec/lib/python3.7/site-packages/click/termui.py", line 449, in style
    return ''.join(bits)
TypeError: sequence item 1: expected str instance, NoneType found
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

I was navigated to OAuth via GitHub in the meantime.

**Comment by judepereira** [comment]
Related to CLI-55 in Sentry.

**Comment by kenneth-reitz** [comment]
this appears to no longer be the case
